/**
 *
 *  CategoryController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "CategoryController.h"
#include <string>


void CategoryController::getOne(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback,
                                Category::PrimaryKeyType &&id)
{
    CategoryControllerBase::getOne(req, std::move(callback), std::move(id));
}


void CategoryController::updateOne(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback,
                                   Category::PrimaryKeyType &&id)
{
    CategoryControllerBase::updateOne(req, std::move(callback), std::move(id));
}


void CategoryController::deleteOne(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback,
                                   Category::PrimaryKeyType &&id)
{
    CategoryControllerBase::deleteOne(req, std::move(callback), std::move(id));
}

void CategoryController::get(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback)
{
    CategoryControllerBase::get(req, std::move(callback));
}

void CategoryController::create(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback)
{
    CategoryControllerBase::create(req, std::move(callback));
}
