/**
 *
 *  FileController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "FileController.h"
#include <string>


void FileController::getOne(const HttpRequestPtr &req,
                            std::function<void(const HttpResponsePtr &)> &&callback,
                            File::PrimaryKeyType &&id)
{
    FileControllerBase::getOne(req, std::move(callback), std::move(id));
}


void FileController::updateOne(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback,
                               File::PrimaryKeyType &&id)
{
    FileControllerBase::updateOne(req, std::move(callback), std::move(id));
}


void FileController::deleteOne(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback,
                               File::PrimaryKeyType &&id)
{
    FileControllerBase::deleteOne(req, std::move(callback), std::move(id));
}

void FileController::get(const HttpRequestPtr &req,
                         std::function<void(const HttpResponsePtr &)> &&callback)
{
    FileControllerBase::get(req, std::move(callback));
}

void FileController::create(const HttpRequestPtr &req,
                            std::function<void(const HttpResponsePtr &)> &&callback)
{
    FileControllerBase::create(req, std::move(callback));
}
