services:
  redis:
    container_name: redis
    image: redis
  user_service:
      container_name: user_service
      build: ..
      environment:
         DOCKER: true
      command: ["/app/build/user_service/user_service"]
      ports:
        - "5555:5555"
      volumes:
        - ../user_service/configs/:/app/user_service/configs/
  file_service:
      container_name: file_service
      build: ..
      environment:
         DOCKER: true
      command: ["/app/build/file_service/file_service"]
      ports:
        - "5556:5556"
      volumes:
        - ../file_service/configs/:/app/file_service/configs/
