services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.5.0'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: 'confluentinc/cp-kafka:7.5.0'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_LOGGERS : kafka.controller=ERROR,state.change.logger=ERROR,kafka=ERROR,org.apache.kafka=ERROR
    command: >
      sh -c "
        wait-for-it.sh  kafka:9092 -- /usr/bin/kafka-topics --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic verify && \
        /usr/bin/kafka-topics --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic status_verify &
        /etc/confluent/docker/run
      "
    volumes:
      - ./wait-for-it.sh:/bin/wait-for-it.sh
  redis:
    container_name: redis
    image: redis
  user_service:
      depends_on:
        - kafka
      container_name: user_service
      build: ..
      environment:
         DOCKER: true
      command: >
        wait-for-it.sh kafka:9092 -- /app/build/user_service/user_service
      ports:
        - "5555:5555"
      volumes:
        - ../user_service/configs/:/app/user_service/configs/
        - ./db-create/:/app/db/
        - ./wait-for-it.sh:/usr/bin/wait-for-it.sh
  file_service:
      depends_on:
        - kafka
      container_name: file_service
      build: ..
      environment:
         DOCKER: true
      command: >
        wait-for-it.sh kafka:9092 -- /app/build/file_service/file_service
      ports:
        - "5556:5556"
      volumes:
        - ../file_service/configs/:/app/file_service/configs/
        - ./db-create/:/app/db/
        - ./wait-for-it.sh:/usr/bin/wait-for-it.sh
