services:
  kafka:
    image: 'bitnami/kafka:3.7.0'
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=S40B8iVtR0umuTyuM1eLjA
      - KAFKA_CFG_NODE_ID=1
  redis:
    container_name: redis
    image: redis
  user_service:
      depends_on:
        - kafka
      container_name: user_service
      build: ..
      environment:
         DOCKER: true
      command: >
        wait-for-it.sh kafka:9092 -- /app/build/user_service/user_service
      ports:
        - "5555:5555"
      volumes:
        - ../user_service/configs/:/app/user_service/configs/
        - ./db-create/:/app/db/
        - ./wait-for-it.sh:/usr/bin/wait-for-it.sh
  file_service:
      depends_on:
        - kafka
      container_name: file_service
      build: ..
      environment:
         DOCKER: true
      command: >
        wait-for-it.sh kafka:9092 -- /app/build/file_service/file_service
      ports:
        - "5556:5556"
      volumes:
        - ../file_service/configs/:/app/file_service/configs/
        - ./db-create/:/app/db/
        - ./wait-for-it.sh:/usr/bin/wait-for-it.sh
