services:
  kafka:
    image: 'bitnami/kafka:3.7.0'
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=S40B8iVtR0umuTyuM1eLjA
      - KAFKA_CFG_NODE_ID=1
  redis:
    container_name: redis
    image: redis
  user_service:
      depends_on:
        - kafka
      container_name: user_service
      build: ..
      environment:
        USER_SERVICE_CONFIG : /app/user_service/configs/config.docker.json
      command: >
        wait-for-it.sh kafka:9092 -- /app/build/user_service/user_service
      ports:
        - "5555:5555"
      volumes:
        - ../user_service/configs/:/app/user_service/configs/
        - ./db-create/:/app/db/
        - ./wait-for-it.sh:/usr/bin/wait-for-it.sh
  file_service:
      depends_on:
        - kafka
      container_name: file_service
      build: ..
      environment:
        FILE_SERVICE_CONFIG: /app/file_service/configs/config.docker.json
      command: >
        wait-for-it.sh kafka:9092 -- /app/build/file_service/file_service
      ports:
        - "5556:5556"
      volumes:
        - ../file_service/configs/:/app/file_service/configs/
        - ./db-create/:/app/db/
        - ./wait-for-it.sh:/usr/bin/wait-for-it.sh
  authentication_service:
    build:
      context: ..
      dockerfile: Dockerfile.sharp 
    container_name: authentication_service
    environment:
      USER_SERVICE_HOST: http://user_service:5555/user
      ASPNETCORE_URLS : http://*:5225
    ports:
      - "5225:5225"
    command: >
      dotnet authentication_service.dll
  gateway:
    build:
      context: ..
      dockerfile: Dockerfile.sharp
    container_name: gateway
    environment:
      ASPNETCORE_URLS: http://*:5231
      ROUTING_CONFIG: /config/routing.json
    volumes:
      - ../gateway/Properties/routing.docker.json:/config/routing.json
    ports:
      - "5231:5231"
    command: >
      dotnet gateway.dll
  int_test:
    build:
      context: ..
      dockerfile: Dockerfile.sharp
    container_name: int_test
    command: >  
      tail -f /dev/null
    volumes:
      - ../int_test/appsettings.docker.json:/out/appsettings.json